{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kube.fullname" . }}
  labels:
    {{- include "kube.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # Force HTTPS redirection
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: "{{ .Values.services.ambrosia.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-ambrosia
                port:
                  number: {{ $.Values.services.ambrosia.service.port }}
    - host: "{{ .Values.services.anubis.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-anubis
                port:
                  number: {{ $.Values.services.anubis.service.port }}
    - host: "{{ .Values.services.hermes.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-hermes
                port:
                  number: {{ $.Values.services.hermes.service.port }}
    - host: "{{ .Values.services.muse.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-muse
                port:
                  number: {{ $.Values.services.muse.service.port }}
{{- end }}