apiVersion: v2
name: ingress
description: NGINX Ingress Controller Configuration for Kubernetes

type: application
version: 0.1.0
appVersion: "1.8.1" # Matches the ingress-nginx controller version used
