apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
data:
  proxy-buffer-size: "128k"
  proxy-body-size: "50m"
  server-tokens: "false"
  use-proxy-protocol: "false"
  use-forwarded-headers: "true"
  enable-real-ip: "true"
  proxy-real-ip-cidr: "0.0.0.0/0"